# Copyright (c) 2023-2024 Antmicro <www.antmicro.com>
# SPDX-License-Identifier: Apache-2.0

stages:
  - test
  - deploy_docs

variables:
  DEBIAN_FRONTEND: noninteractive
  SCALENODE_RAM: 10240
  SCALENODE_CPU: 8
  SCALENODE_DISK: 20

lint:
  variables:
    SCALENODE_RAM: 4096
    SCALENODE_CPU: 4
  stage: test
  image: debian:bookworm
  script:
    - ./.github/scripts/ci.sh lint

test_python_3_8:
  stage: test
  image: debian:bookworm
  script:
    - ./.github/scripts/ci.sh test_python 3.8

test_python_3_9:
  stage: test
  image: debian:bookworm
  script:
    - ./.github/scripts/ci.sh test_python 3.9

test_python_3_10:
  stage: test
  image: debian:bookworm
  script:
    - ./.github/scripts/ci.sh test_python 3.10

test_python_3_11:
  stage: test
  image: debian:bookworm
  script:
    - ./.github/scripts/ci.sh test_python 3.11

test_python_3_12:
  stage: test
  image: debian:bookworm
  script:
    - ./.github/scripts/ci.sh test_python 3.12

package_test:
  variables:
    SCALENODE_CPU: 4
    SCALENODE_RAM: 8192
  stage: test
  image: debian:bookworm
  script:
    - ./.github/scripts/ci.sh package_dist

examples:
  variables:
    SCALENODE_CPU: 6
    SCALENODE_RAM: 8192
  stage: test
  image: debian:bookworm
  script:
    - ./.github/scripts/ci.sh examples
  artifacts:
    paths:
      - examples/**/build

package_cores:
  variables:
    SCALENODE_CPU: 4
    SCALENODE_RAM: 8192
  stage: test
  image: debian:bookworm
  script:
    - ./.github/scripts/ci.sh package_cores
    - tar -cf build/cores_export.tar -C build/export .
  artifacts:
    paths:
      - build/cores_export.tar

pyright_check:
  variables:
    SCALENODE_RAM: 6144
    SCALENODE_CPU: 4
  stage: test
  image: debian:bookworm
  script:
    - ./.github/scripts/ci.sh pyright_check
  allow_failure: true

changelog_check:
  image: debian:bookworm
  variables:
    SCALENODE_RAM: 3072
    SCALENODE_CPU: 3
  stage: test
  script:
    - ./.github/scripts/ci.sh changelog_check
  allow_failure: true

build_docs:
  variables:
    SCALENODE_RAM: 18432
    SCALENODE_CPU: 5
  image: debian:bookworm
  stage: test
  script:
    - ./.github/scripts/ci.sh docs
    - tar cf "$CI_DOCS_ARCHIVE" -C docs/build/html/ .
  artifacts:
    paths:
      - docs/build
      - $CI_DOCS_ARCHIVE

deploy_docs:
  image: debian:bookworm
  variables:
    GIT_STRATEGY: none
    SCALENODE_RAM: 2048
    SCALENODE_CPU: 1
  dependencies: [ build_docs ]
  stage: deploy_docs
  tags: ['docs']
  script: echo 'Deploying docs'
  artifacts:
    paths:
      - $CI_DOCS_ARCHIVE

include:
  - project: 'repositories/topwrap'
    ref: internal_ci_yaml
    file: '/internal.yml'
